name: Deploy Documentation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install Documentation Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autoapi

      - name: Build Sphinx Documentation
        run: |
          cd docs
          make html

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/_build/html
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
